WITH T(StyleID, ID, Nome) AS (
	SELECT 1, 1, 'Rhuan' UNION ALL
	SELECT 1, 2, 'André' UNION ALL
	SELECT 1, 3, 'Ana' UNION ALL
	SELECT 1, 4, 'Maria' UNION ALL
	SELECT 1, 5, 'Letícia' UNION ALL
	SELECT 1, 6, 'Lari' UNION ALL
	SELECT 1, 7, 'Edson' UNION ALL
	SELECT 1, 8, 'Marcos' UNION ALL
	SELECT 1, 9, 'Daisy'
)
SELECT *
	,ROW_NUMBER() OVER(PARTITION BY StyleID ORDER BY ID) AS "ROW_NUMBER"
	,RANK() OVER(PARTITION BY StyleID ORDER BY ID) AS "RANK"
	,DENSE_RANK() OVER(PARTITION BY StyleID ORDER BY ID) AS "DENSE_RANK"
	,PERCENT_RANK() OVER(PARTITION BY StyleID ORDER BY ID) AS "PERCENT_RANK"
	,CUME_DIST() OVER(PARTITION BY StyleID ORDER BY ID) AS "CUME_DIST"
	,CUME_DIST() OVER(PARTITION BY StyleID ORDER BY ID DESC) AS "CUME_DIST_DESC"
	,FIRST_VALUE(Nome) OVER(PARTITION BY StyleID ORDER BY ID) AS "FIRST_VALUE"
	,LAST_VALUE(Nome) OVER(PARTITION BY StyleID ORDER BY ID) AS "LAST_VALUE"
	,NTH_VALUE(Nome, 3) OVER(PARTITION BY StyleID ORDER BY ID) AS "NTH_VALUE"
	,NTILE(3) OVER(ORDER BY StyleID) AS "NTILE"
	,LAG(Nome, 1) OVER(ORDER BY ID) AS "LAG"
	,LEAD(Nome, 1) OVER(ORDER BY ID) AS "LEAD"
FROM T

